In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("iqsize.csv")
df

    PIQ   Brain  Height  Weight
0   124   81.69    64.5     118
1   150  103.84    73.3     143
2   128   96.54    68.8     172
3   134   95.15    65.0     147
4   110   92.88    69.0     146
5   131   99.13    64.5     138
6    98   85.43    66.0     175
7    84   90.49    66.3     134
8   147   95.55    68.8     172
9   124   83.39    64.5     118
10  128  107.95    70.0     151
11  124   92.41    69.0     155
12  147   85.65    70.5     155
13   90   87.89    66.0     146
14   96   86.54    68.0     135
15  120   85.22    68.5     127
16  102   94.51    73.5     178
17   84   80.80    66.3     136
18   86   88.91    70.0     180
19   84   90.59    76.5     186
20  134   79.06    62.0     122
21  128   95.50    68.0     132
22  102   83.18    63.0     114
23  131   93.55    72.0     171
24   84   79.86    68.0     140
25  110  106.25    77.0     187
26   72   79.35    63.0     106
27  124   86.67    66.5     159
28  132   85.78    62.5     127
29  137   94.96    67.0     191
30  110   99.79    75.5     192
31   86   88.00    69.0     181
32   81   83.43    66.5     143
33  128   94.81    66.5     153
34  124   94.94    70.5     144
35   94   89.40    64.5     139
36   74   93.00    74.0     148
37   89   93.59    75.5     179

In [3]:
df.describe()

              PIQ       Brain     Height      Weight
count   38.000000   38.000000  38.000000   38.000000
mean   111.342105   90.675789  68.421053  151.052632
std     22.597867    7.256279   3.993790   23.478509
min     72.000000   79.060000  62.000000  106.000000
25%     89.250000   85.485000  66.000000  135.250000
50%    115.000000   90.540000  68.000000  146.500000
75%    128.000000   94.955000  70.375000  172.000000
max    150.000000  107.950000  77.000000  192.000000

In [5]:
(df["Weight"] / df["Height"]).mean()

2.201361769108894